/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/armchair.glb --transform 
Files: public/models/armchair.glb [3.63MB] > armchair-transformed.glb [622.83KB] (83%)
Author: rickmaolly (https://sketchfab.com/rickmaolly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/armchair--leather-c0755830a1d54d27b86a80c335ccc9c1
Title: Armchair_ Leather
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Armchair(props) {
  const { nodes, materials } = useGLTF("/models/armchair-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane001_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/armchair-transformed.glb");
