/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/room.glb --transform 
Files: public/models/room.glb [5.2MB] > room-transformed.glb [727.78KB] (86%)
Author: SrMonteiro (https://sketchfab.com/crispimrafael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neusa-frois-916185bb2d4c48829591ba95958b9dcd
Title: Neusa Frois
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/room-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Line001_Material_#2143567293_0"].geometry}
        material={materials.Material_2143567293}
        position={[-0.575, 1.525, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Group_051_Material_#64_0"].geometry}
        material={materials.PaletteMaterial001}
        position={[0.446, 1.076, -6.618]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Obj3d66-707242-3-267__0"].geometry}
        material={materials["Obj3d66-707242-3-267__0"]}
        position={[0.439, 0.38, 6.496]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={
          nodes["Obj3d66-707242-32-41_Mat3d66-707242-13-5970_0"].geometry
        }
        material={materials.PaletteMaterial002}
        position={[1.755, 0.851, 2.986]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Object280_Material_#2143566212_0"].geometry}
        material={materials.PaletteMaterial003}
        position={[-0.568, 3.002, 0.598]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["_72_Material_#2143567290_0"].geometry}
        material={materials.Material_2143567290}
        position={[1.877, 0.903, -4.996]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Box076_Material_#2143567292_0"].geometry}
        material={materials.Material_2143567292}
        position={[-0.74, 1.525, 1.37]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={
          nodes["Obj3d66-707242-43-731_Material_#2143567294_0"].geometry
        }
        material={materials.Material_2143567294}
        position={[-0.693, 1.497, 0.602]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Box065_Material_#2143567291_0"].geometry}
        material={materials.Material_2143567291}
        position={[2.226, 1.528, 1.906]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["_313_Material_#2146801357_0"].geometry}
        material={materials.Material_2146801357}
        position={[1.078, 1.126, 6.769]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[0.032, 0.025, 0.032]}
      />
      <mesh
        geometry={nodes["Box077_Material_#2146801360_0"].geometry}
        material={materials.Material_2146801360}
        position={[-2.075, 0, 1.552]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Object285_Material_#2146801358_0"].geometry}
        material={materials.Material_2146801358}
        position={[1.078, 1.126, 6.769]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[0.032, 0.025, 0.032]}
      />
      <mesh
        geometry={nodes["Object286_Material_#2146801359_0"].geometry}
        material={materials.Material_2146801359}
        position={[1.078, 1.126, 6.769]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[0.032, 0.025, 0.032]}
      />
      <instancedMesh
        args={[
          nodes["5#1_011_Material_#3524_0"].geometry,
          materials.PaletteMaterial002,
          36,
        ]}
        instanceMatrix={nodes["5#1_011_Material_#3524_0"].instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/room-transformed.glb");
